### ISSUE TITLE
showCloseButton visual bug with Firefox

### ISSUE THREAD

**Issue by akikesulahti** [Broadcom/bdc-walkthrough#1]
**Description**
Popup close button (showCloseButton) has a visual bug with latest Firefox. It looks like checkbox with dot inside.
Chrome shows it properly like "X".

**Your environment**
Windows 10 Enterprice, Version 1803
Firefox 74.0 (64-bit) (Firefox is up to date)

**Minimal reproduction**
Go to your stackblitz example1 with Firefox:
https://angular-bdc-walkthrough.stackblitz.io/example1

**Comment by amirlpro** [comment]
Fixed
